name: dav1d

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install nasm
      uses: ilammy/setup-nasm@v1
    - name: Install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: actions/setup-python@v2
    - name: Install pip packages
      run: |
        pip install -U pip
        pip install -U wheel setuptools
        pip install -U meson ninja
    - name: Install dav1d
      env:
        DAV1D_DIR: dav1d_dir
      run: |
        git clone --branch 1.0.0 --depth 1 https://code.videolan.org/videolan/dav1d.git
        cd dav1d
        meson build -Dprefix=$HOME/$DAV1D_DIR --buildtype release
        ninja -C build
        ninja -C build install
    - name: Run tests
      env:
        DAV1D_DIR: dav1d_dir
        PKG_PATH: lib/x86_64-linux-gnu/pkgconfig
      run: |
        export PKG_CONFIG_PATH=$HOME/$DAV1D_DIR/$PKG_PATH:$PKG_CONFIG_PATH
        cargo test --all-features
